codemagic new script workflow

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -12,8 +12,6 @@ workflows:
         node: latest
         CM_CLONE_DEPTH: 8
         CM_PULL_REQUEST: true
-        XCODE_WORKSPACE: exploreApp
-        XCODE_SCHEME: exploreApp
     triggering:
       events:
         - push
@@ -39,14 +37,6 @@ workflows:
           prev_tag=$(git for-each-ref --sort=-creatordate --format '%(objectname)' refs/tags | sed -n 2p )
           notes=$(git log --oneline "$branch" --pretty=format:"- %s" "$prev_tag"..HEAD)
           echo "[Explore App - $branch] \n\nNotes: \n$notes" | tee release_notes.txt
-      # - name: Display changes on pull request
-      #   script: |
-      #     if [ "$CM_PULL_REQUEST" != "false" ]; then
-      #       git fetch origin +refs/heads/*:refs/remotes/origin/*
-      #       # sesuain variable name di env variable yg di set codemagic
-      #       git log origin/${CM_PULL_REQUEST_BASE_BRANCH:-main}...HEAD --oneline
-      #       # ganti branchnya
-      #     fi
       - name: pre_build_script
         script: |
           #!/usr/bin/env sh
@@ -78,15 +68,8 @@ workflows:
           # export LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
           # cd hello_world/android/ && ./gradlew assembleDebug
           cd android && ./gradlew assembleRelease
-      - name: Build iOS release
-        script: |
-          # build iOS
-            cd ios
-            pod install
-            xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
     artifacts:
       - android/app/build/outputs/**/*.apk
-      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
     publishing:
       # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
       email:
@@ -103,29 +86,95 @@ workflows:
           groups: 
             - appTester # following group tester in firebase
           artifact_type: 'apk'
+      # scripts:
+      #   - name: Discord notification
+      #     script: | 
+      #       set -ex
+      #       APP_LINK=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name=="app.apk") | .url')
+          
+      #       # Get first 7 digits of commit number
+      #       COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')
 
+      #       # Get commit message
+      #       COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT)
+            
+      #       # Get commit author
+      #       AUTHOR=$(git show -s --format='%ae' $CM_COMMIT)
+            
+      #       # Publish the notification
+      #       curl -H "Content-Type: multipart/form-data" \
+      #       -F 'payload_json={"username" : "codemagic-bot", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK"'\n\n"}' \
+      #       -F "file1=@release_notes.txt" \
+      #       $WEBHOOK_URL
+  react-native-ios:
+    name: React Native iOS
+    max_build_duration: 120
+    environment:
+      groups:
+        - keystore credentials
+        - firebase_credentials
+        - discord_credentials 
+      vars:
+        PACKAGE_NAME: 'com.exploreApp' # <-- Put your package name here e.g. com.domain.myapp
+        node: latest
+        CM_CLONE_DEPTH: 8
+        CM_PULL_REQUEST: true
+        XCODE_WORKSPACE: exploreApp
+        XCODE_SCHEME: exploreApp
+    triggering:
+      events:
+        - push
+        - tag
+        - pull_request
+      branch_patterns:
+        - pattern: main
+          include: true
+          source: true
+    scripts:
+      - name: Generating release notes with git commits
+        script: | 
+          git fetch --all --tags
+          branch=$(git branch --show-current)
+          prev_tag=$(git for-each-ref --sort=-creatordate --format '%(objectname)' refs/tags | sed -n 2p )
+          notes=$(git log --oneline "$branch" --pretty=format:"- %s" "$prev_tag"..HEAD)
+          echo "[Explore App - $branch] \n\nNotes: \n$notes" | tee release_notes.txt
+      - name: pre_build_script
+        script: |
+          #!/usr/bin/env sh
+          export VARNAME="my value"
+          set -e # exit on first failed command
+          echo $ANDROID_FIREBASE_SECRET | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
+          # echo $IOS_FIREBASE_SECRET | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
+      - name: Install yarn dependencies
+        script: |
+          yarn       
+      - name: Build iOS release
+        script: |
+          # build iOS
+            cd ios
+            pod install
+            xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
+      - name: Build ipa for distribution
+        script: | 
+          xcode-project build-ipa \
+            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE.xcworkspace" \
+            --scheme "$XCODE_SCHEME"
+    artifacts:
+      - build/ios/ipa/*.ipa
+      - /tmp/xcodebuild_logs/*.log
+      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
+    publishing:
+      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
+      email:
+        recipients:
+          - ahmadfathonizumaro@gmail.com
+          - toniebe48@gmail.com
+        notify:
+          success: true # To not receive a notification when a build succeeds
+          failure: false # To not receive a notification when a build fails
+      firebase:
+        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
         ios:
-          # Add your iOS app id retrieved from Firebase console
           app_id: 1:953175852743:ios:9c5ffe705e8347caf1a0e2
           groups:
             - appTester
-      scripts:
-        - name: Discord notification
-          script: | 
-            set -ex
-            APP_LINK=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name=="app.apk") | .url')
-          
-            # Get first 7 digits of commit number
-            COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')
-
-            # Get commit message
-            COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT)
-            
-            # Get commit author
-            AUTHOR=$(git show -s --format='%ae' $CM_COMMIT)
-            
-            # Publish the notification
-            curl -H "Content-Type: multipart/form-data" \
-            -F 'payload_json={"username" : "codemagic-bot", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK"'\n\n"}' \
-            -F "file1=@release_notes.txt" \
-            $WEBHOOK_URL
