add codemagic credential

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -89,29 +89,46 @@ workflows:
       scripts:
         - name: Discord notification
           script: | 
-            set -ex
-            APP_LINK=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name=="app-release.apk") | .url')
-            # APP_LINK=android/app/build/outputs/**/*.apk
-            # Get first 7 digits of commit number
-            COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')
+           set -ex
+           # Your API Token for authentication
 
-            # Get commit message
-            COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT)
-            
-            # Get commit author
-            AUTHOR=$(git show -s --format='%ae' $CM_COMMIT)
-            
-            # make public artifact_
-            curl -H "Content-Type: application/json" \
-            -H "x-auth-token: <API Token>" \
-            -d '{"expiresAt": 1735664399}' \
-            -X POST $APP_LINK/public-url
+           # Get the public URL for the artifact
+           response=$(curl -H "Content-Type: application/json" \
+                -H "x-auth-token: $API_TOKEN" \
+                -d '{"expiresAt": 1735664399}' \
+                -X POST -w "\n%{http_code} %{response_code}" $APP_LINK/public-url)
 
-            # Publish the notification
-            curl -H "Content-Type: multipart/form-data" \
-            -F 'payload_json={"username" : "explore-app deployment", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK/public-url"'\n\n"}' \
-            -F "file1=@release_notes.txt" \
-            $WEBHOOK_URL
+           # Extract the HTTP status code
+           status_code=$(echo "$response" | awk '{print $1}')
+
+           # Extract the response body without the status code
+           response_body=$(echo "$response" | sed '$d')
+
+           # Check if the request was successful (HTTP status code 2xx)
+           if [[ $status_code -ge 200 && $status_code -lt 300 ]]; then
+                # Parse the JSON response to extract the 'url' field
+                APP_LINK=$(echo "$response_body" | jq -r '.url')
+                echo "Artifact URL: $APP_LINK"
+           else
+                echo "Failed to retrieve the artifact URL. Status code: $status_code"
+                exit 1
+            fi
+
+           # Get first 7 digits of commit number
+           COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')
+
+           # Get commit message
+           COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT)
+            
+           # Get commit author
+           AUTHOR=$(git show -s --format='%ae' $CM_COMMIT)
+    
+
+           # Publish the notification
+           curl -H "Content-Type: multipart/form-data" \
+           -F 'payload_json={"username" : "explore-app deployment", "content": "**Commit:** `'"$COMMIT"'`\n\n**Commit message:** '"$COMMIT_MESSAGE"'\n\n**Branch:** '"$CM_BRANCH"'\n\n**Author:** '"$AUTHOR"'\n\n**Artifacts: **\n\n'"$APP_LINK/public-url"'\n\n"}' \
+           -F "file1=@release_notes.txt" \
+           $WEBHOOK_URL
   # react-native-ios:
   #   name: React Native iOS
   #   max_build_duration: 120
