comment publishing email and firebase

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -23,14 +23,27 @@ workflows:
           include: true
           source: true
     scripts:
-      - name: Create a changelog
+      - name: Exit build if keyword not defined
         script: | 
-          if [[ -z ${CM_PREVIOUS_COMMIT} ]]
+          set -e
+          set -x
+          export COMMIT_MSG=$(git log -1 --pretty=%B)
+          echo COMMIT_MSG
+          if [[ $COMMIT_MSG != *"buildcd"* ]]
             then
-             echo "No finished builds found to generate changelog" | tee release_notes.txt
-            else
-             echo "$(git-changelog generate --previous-commit $CM_PREVIOUS_COMMIT)" | tee release_notes.txt
+              echo "Commit needs to include 'buildcd' in it's message."
+              exit 1
+            else 
+              echo "Commit message includes 'buildcd', moving forward..."
           fi
+      # - name: Create a changelog
+      #   script: | 
+      #     if [[ -z ${CM_PREVIOUS_COMMIT} ]]
+      #       then
+      #        echo "No finished builds found to generate changelog" | tee release_notes.txt
+      #       else
+      #        echo "$(git-changelog generate --previous-commit $CM_PREVIOUS_COMMIT)" | tee release_notes.txt
+      #     fi
       - name: Generating release notes with git commits
         script: | 
           git fetch --all --tags
@@ -73,20 +86,20 @@ workflows:
       - android/app/build/outputs/**/*.apk
     publishing:
       # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
-      email:
-        recipients:
-          - ahmadfathonizumaro@gmail.com
-          - toniebe48@gmail.com
-        notify:
-          success: true # To not receive a notification when a build succeeds
-          failure: false # To not receive a notification when a build fails
-      firebase:
-        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
-        android: 
-          app_id: 1:953175852743:android:add8ee72c4c87177f1a0e2
-          groups: 
-            - "codemagic-tester" # following group tester in firebase
-          artifact_type: 'apk'
+      # email:
+      #   recipients:
+      #     - ahmadfathonizumaro@gmail.com
+      #     - toniebe48@gmail.com
+      #   notify:
+      #     success: true # To not receive a notification when a build succeeds
+      #     failure: false # To not receive a notification when a build fails
+      # firebase:
+      #   firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
+      #   android: 
+      #     app_id: 1:953175852743:android:add8ee72c4c87177f1a0e2
+      #     groups: 
+      #       - "codemagic-tester" # following group tester in firebase
+      #     artifact_type: 'apk'
       scripts:
         - name: Discord notification
           script: | 
@@ -122,7 +135,7 @@ workflows:
            COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')
 
            # Get commit message
-           COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT)
+           COMMIT_MESSAGE=$(git log --format=%B -n 1 $CM_COMMIT | sed 's/_NEWLINE_/\\n/g')
             
            # Get commit author
            AUTHOR=$(git show -s --format='%ae' $CM_COMMIT)
