trace response public url artifact

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -100,20 +100,21 @@ workflows:
                 -d '{"expiresAt": 1735664399}' \
                 -X POST -w "\n%{http_code} %{response_code}" $APP_LINK/public-url)
 
-           # Extract the response body without the status code
-           response_body=$(echo "$response" | sed '$d')
+           echo "API Response: $response"
 
-          
            # Extract the response body
            APP_LINK=$(echo "$response" | jq -r '.url')
 
+           echo "Extracted URL: $APP_LINK"
+
            # Check if the URL is non-empty
            if [ -n "$APP_LINK" ]; then
-            echo "Artifact URL: $APP_LINK"
+                echo "Artifact URL: $APP_LINK"
            else
-            echo "Failed to retrieve the artifact URL."
-            exit 1
+                echo "Failed to retrieve the artifact URL."
+                exit 1
            fi
+
 
            # Get first 7 digits of commit number
            COMMIT=$(echo "${CM_COMMIT}" | sed 's/^\(........\).*/\1/;q')
